#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     SonarSensor,    sensorSONAR)
#pragma config(Sensor, S3,     LightSensor,    sensorLightActive)
#pragma config(Sensor, S4,     Touch,          sensorTouch)
#pragma config(Motor,  motorA,          vacuumA,       tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          vacuumB,       tmotorNXT, openLoop, reversed)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     leftMotor,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightMotor,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma systemFile  // eliminates warning for "unreferenced" functions

//
// Functions.c
//
// Shared functions between Autonomous and Teleop modes
//

//
// Drive the robot with left and right joysticks
//
// @param left the power value for the right side of the drivetrain
// @param right the power value for the right side of the drivetrain
//
void TankDrive(int left, int right)
{
	motor[leftMotor] = left;
	motor[rightMotor] = right;
}

//
// Arcade style driving of the robot
//
// @param throttle the forward-reverse movement value of the robot
// @param turn the left-right movement value of the robot
void ArcadeDrive(int throttle, int turn)
{
	motor[leftMotor] = throttle + turn;
	motor[rightMotor] = throttle - turn;
}

//
// Create a deadzone or deadband for the input value
//
// @param value the value to check
// @param db the deadzone for the value
// @return 0 if value is inside the deadband, otherwise the value
//
int deadband(int value, int db)
{
	//
	// This uses the ternary operator '?:'. It takes three values, and works
	// as follows:
	//
	// int x = (condition) ? value1 : value2;
	//
	// If 'condition' is true, then the expression evaluates to 'value1', else
	// it evaluates to 'value2'. It is similar to the following if-else statement
	//
	// int x;
	// if (condition)
	// 		x = value1;
	// else
	// 		x = value2;
	//
	// The version used here is more compact, and is a good way to ilustrate usage
	// of the ternary operator.
	//
	return (abs(value) < db) ? 0 : value;
}
